### ISSUE TITLE
Unable to run example unless "c_SetPhoenixDiagnosticsStartTime(-1);" is commented out.

### ISSUE THREAD

**Issue by vatbrain** [CrossTheRoadElec/Phoenix-Linux-SocketCAN-Example#15]
Running a stripped down version of example.cpp modified for the VictorSPX controller produces the following messages on the console:
>CTR: Firm Vers could not be retrieved. Use Phoenix Tuner to check ID and firmware(CRF) version. 
>	Victor SPX 21
 
and does not function properly unless the statement: 

`c_SetPhoenixDiagnosticsStartTime(-1); // disable diag server, instead we will use the diag server stand alone application that Tuner installs`

is commented out and the standalone diagnostic server is uninstalled from the host (in this case raspberry pi).

**Comment by JCaporuscio** [comment]
We're working on diagnosing the cause in order to implement a fix.

In the meantime, using the in-program diag server without the standalone version will function as a workaround.

**Comment by JCaporuscio** [comment]
This was fixed when the example was updated to Phoenix 5.21.1.

We still recommend leaving it commented out so you can take advantage of the diagnostic server that runs in the application background, but if you'd prefer to disable it you can now uncomment the `c_SetPhoenixDiagnosticsStartTime(-1);` call and the rest of the application will still work.
