### ISSUE TITLE
Socket Can Error: No such device or address

### ISSUE THREAD

**Issue by QuantumRoboticsURC** [CrossTheRoadElec/Phoenix-Linux-SocketCAN-Example#17]
Hello!
I implemented the code in my JetsonTX2 using a sn65hvd230 transceiver. The problem is when I run twice the program. 
When I run the program at first time, it works well and I can see the controllers working, also I can configure using the Phoenix Tunner program.
![image](https://user-images.githubusercontent.com/74209324/103389745-5e457880-4ad6-11eb-9cf4-f584f355451d.png)

The second time I run the program, I got an error which says "Socket Can Error: No such device or address", this after the message "using interface: can0" started flooding.

![image](https://user-images.githubusercontent.com/74209324/103389735-508ff300-4ad6-11eb-8593-7f2026fc6ee9.png)

To solve the problem, I have to restart my Jetson but that is not the goal. What can I do?

**Comment by RoopanJK** [comment]
Hey @QuantumRoboticsURC , Could you please mention how you've solved this issue. I'm also facing the same thing here.

**Comment by ShikurM56** [comment]
Hello @RoopanJK 

Every time you want to restart the application you have to right click on the terminal and then click on "exit". This will close correctly the terminal and will avoid the flooding messages that you got when re-open the terminal and run the program. 
If you try to close the application with Ctrl + C or Ctrl + Z, it won't close correctly and you will have to restart your CPU.

This is the script that we run after booting up our jetson tx2
https://github.com/QuantumRoboticsURC/bus_can_drive/blob/main/src/canableStart.sh

And this is the script to control some drive motors and arm control
https://github.com/QuantumRoboticsURC/bus_can_drive/blob/main/src/drive_can.cpp

**Comment by RoopanJK** [comment]
Hey @ShikurM56, thanks for your code, greatly helpful. And by the way I don't get the flooded messages only when I restart the program, it gets posted even the first time I start the program after booting into my Orin nano. 

And BTW I remote to my orin nano via ssh I don't see how I'll right click and exit I could close the tmux buffer though will that help? Will give that a try too
Thanks a lot for your help. :)

**Comment by RoopanJK** [comment]
> Hey @ShikurM56, thanks for your code, greatly helpful. And by the way I don't get the flooded messages only when I restart the program, it gets posted even the first time I start the program after booting into my Orin nano.
> 
> And BTW I remote to my orin nano via ssh I don't see how I'll right click and exit I could close the tmux buffer though will that help? Will give that a try too Thanks a lot for your help. :)

![image](https://github.com/CrossTheRoadElec/Phoenix-Linux-SocketCAN-Example/assets/82260000/413a7a74-8bb5-4f64-bc05-ce699e62d71d)
In addition to the flooding message "using interface: can0", the connection with the TalonFX gets disconnected after a said duration every time with the above attached error.

I modified your code and used the library files in your repo but am facing this error.
