### ISSUE TITLE
undefined reference to pthread_cond_clockwait@GLIBC_2.30'

### ISSUE THREAD

**Issue by Codster130** [CrossTheRoadElec/Phoenix-Linux-SocketCAN-Example#22]
When building the example.cpp, I get error 
`/usr/bin/ld: ../lib/arm32/libCTRE_PhoenixCCI.so: undefined reference to 'pthread_cond_clockwait@GLIBC_2.30'
collect2: error: ld returned 1 exit status`
`make[2]: *** [CMakeFiles/example.dir/build.make:87: ../bin/example] Error 1`
`make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/example.dir/all] Error 2`
`make: *** [Makefile:84: all] Error 2`

**Comment by JCaporuscio** [comment]
What hardware platform are you using, and what OS are you running?

**Comment by Codster130** [comment]
Sounds good! Just tested and it works.
Could you make an update to the readme for future reference so others don't run into this issue? 
Thanks for clearing this in a timely manner.

**Comment by JCaporuscio** [comment]
I've made a readme update that should help clarify the requirement moving forward.

There's also a decent chance the readme will be re-written in the near future as we streamline some of the steps and project setup.

Going to close this issue for now, feel free to open a new one if you run in to any other issues.
