### ISSUE TITLE
CAN Bus Message Fields

### ISSUE THREAD

**Issue by half-potato** [CrossTheRoadElec/Phoenix-Linux-SocketCAN-Example#9]
Can I have the CAN bus message fields and field types for the victor spx?

**Comment by JCaporuscio** [comment]
This was answered in your other issue tracker...
https://github.com/CrossTheRoadElec/Phoenix-platform/issues/1#issuecomment-485294908

> The frame decoding is done in Phoenix-CCI, which is closed-source.
> [snip]
> We provide Platform shared objects for socket-can, or you can implement one yourself if you have a custom CAN bus interface.
>
>If you are implementing from scratch, you can look at the frame decoding in Phoenix-netmf and port from c#. Use the 11.X Victor SPX firmware if you take this route.
http://www.ctr-electronics.com/victor-spx.html#product_tabs_technical_resources

Relevant link to Phoenix-netmf:
https://github.com/CrossTheRoadElec/Phoenix-netmf


If there's something specific you're trying to accomplish, send an e-mail to our support address and we can help you more effectively.
http://www.ctr-electronics.com/contacts-us

**Comment by JCaporuscio** [comment]
Closing as the question has been answered.
